language: python

python:
    - 2.7
    - 3.5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - swig
      - liblapack-dev

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.conda

before_install:
    # Set up a conda environment for faster set-up of standard libraries
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    # Set the C++ and Fortran compilers 
    - export CXX=g++-4.8 
    - export F90=gfortran-4.8

install:
    # Download and install MultiNest
    - git clone http://github.com/JohannesBuchner/MultiNest
    - cd MultiNest
    - cmake -DCMAKE_Fortran_COMPILER=gfortran-4.8
    - make
    - export LD_LIBRARY_PATH=$(pwd)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    # Create and activate a test environment
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    # Python setup
    - conda install --yes numpy Cython mpi4py
    - pip install numpy matplotlib healpy pymultinest jupyter corner mpmath pytest pytest-cov codecov coverage
    - make build  # Build Cython
    - python setup.py install # Install locally
    # Download Fermi data
    - cd ..
    - wget https://dspace.mit.edu/bitstream/handle/1721.1/105492/fermi_data.tar.gz
    - tar -xvf fermi_data.tar.gz
script:
    - coverage run tests/test_all.py
after_success:
    - codecov
